[package]
name = "cch23-dcorreia"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.1"
shuttle-axum = { version = "0.34.1", default-features = false, features = ["axum-0-7"] }
shuttle-runtime = "0.34.1"
tokio = "1.34.0"
tracing = "0.1.40"
serde = { version = "1.0.193", features = ["derive"] }
ordered-float = "4.1.1"
